In [9]:
import pickle
import pandas as pd

In [13]:
df = pd.read_csv('./tmi_temp_user_data.csv')

In [15]:
values = ['attr', 'sinc', 'intel', 'fun', 'amb', 'shar']

In [22]:
df = df.drop(index=92)

In [28]:
df

,Unnamed: 0,iid,gender,age,field,attr,sinc,intel,fun,amb,...,museums,reading,shopping,dining,theater,concerts,movies,tv,music,goal
0,1,2,Female,24.0,1.0,45.0,5.0,25.0,20.0,0.0,...,8.0,10.0,3.0,10.0,9.0,7.0,8.0,1.0,8.0,1.0
1,18,19,Male,28.0,8.0,50.0,0.0,25.0,10.0,0.0,...,5.0,8.0,7.0,10.0,1.0,7.0,7.0,1.0,7.0,4.0
2,19,20,Male,24.0,8.0,100.0,0.0,0.0,0.0,0.0,...,9.0,8.0,5.0,10.0,8.0,6.0,8.0,3.0,6.0,1.0
3,30,31,Female,24.0,1.0,35.0,10.0,20.0,20.0,10.0,...,7.0,6.0,10.0,10.0,8.0,6.0,8.0,8.0,7.0,1.0
4,34,35,Female,25.0,2.0,20.0,23.0,23.0,22.0,7.0,...,8.0,7.0,8.0,8.0,8.0,7.0,8.0,9.0,7.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,531,533,Male,26.0,5.0,25.0,25.0,25.0,13.0,12.0,...,5.0,3.0,2.0,7.0,5.0,6.0,7.0,1.0,7.0,2.0
88,535,537,Male,22.0,5.0,20.0,5.0,25.0,25.0,5.0,...,8.0,10.0,10.0,10.0,10.0,10.0,10.0,8.0,10.0,1.0
89,537,539,Male,22.0,1.0,30.0,10.0,20.0,15.0,15.0,...,9.0,8.0,7.0,9.0,7.0,7.0,9.0,6.0,7.0,1.0
90,539,541,Male,23.0,5.0,40.0,30.0,0.0,20.0,0.0,...,3.0,3.0,9.0,8.0,5.0,10.0,10.0,10.0,9.0,3.0
91,545,547,Male,30.0,8.0,25.0,20.0,20.0,20.0,0.0,...,8.0,9.0,6.0,7.0,9.0,9.0,8.0,4.0,9.0,2.0

In [ ]:
1 ~ 10
'attr', 'sinc', 'intel', 'fun', 'amb', 'shar'

30 => 100     100/30 = 3.33

        5, 5, 5, 5, 5, 5
        16.65,16.65,16.65,16.65,16.65,16.65